# name: CI/CD for Online Inference with FaaS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   inference-pipeline:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       - name: Python setup
#         uses: actions/setup-python@v5
#         with:
#           python-version: 3.12
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           aws-access-key-id: ${{ secrets.ACCESS_KEY }}
#           aws-secret-access-key: ${{ secrets.SECRET_KEY }}
#           aws-region: us-east-1
#       - name: Login to ECR
#         run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_URL }}
#       - name: Create ECR repository
#         run: aws ecr create-repository --repository-name "utec-mlops/${{ github.actor }}/online-prediction-faas"



# repository_name = f"utec-mlops/{USERNAME}/online-prediction"

# !aws ecr create-repository --repository-name $repository_name

# !docker build -t $repository_name .

# ecr_url = "654654589924.dkr.ecr.us-east-1.amazonaws.com"
# tag_name = f"{repository_name}:latest"
# full_tag_name = f"{ecr_url}/{tag_name}"

# !docker tag $tag_name $full_tag_name

# !docker push $full_tag_name

# function_name = f"mlops-utec-{USERNAME}-online-prediction"
# print(function_name)
# lambda_role = "arn:aws:iam::654654589924:role/utec-lambda-mlops-role"