name: AWS Connection Test

on:
  push:
    branches:
      - main

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: Test AWS CLI connection
        run: aws s3 ls

      - name: Get GitHub Username
        run: echo "GitHub Username" #: ${{ github.actor }}"